
/* 
 Copyright (C) 2007 Ferdinando Ametrano
 Copyright (C) 2006 Eric Ehlers

 This file is part of QuantLib, a free-software/open-source library
 for financial quantitative analysts and developers - http://quantlib.org/

 QuantLib is free software: you can redistribute it and/or modify it
 under the terms of the QuantLib license.  You should have received a
 copy of the license along with this program; if not, please email
 <quantlib-dev@lists.sf.net>. The license is also available online at
 <http://quantlib.org/license.shtml>.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the license for more details.
*/

// Excel functions coded by hand, to be registered with Excel
// alongside the autogenerated functions.

#include <qlxl/functions/functioncount.hpp>
#include <ohxl/objecthandlerxl.hpp>
#include <xlsdk/xlsdkdefines.hpp>
#include <qlxl/session.hpp>
#include <qlxl/conversions/all.hpp>
#include <oh/enumerations/typefactory.hpp>
#include <qlo/enumerations/factories/calendarfactory.hpp>
#include <ql/time/date.hpp>
#include <ql/time/calendar.hpp>
#include <ql/optional.hpp>
#include <qlo/loop/loop_calendar_manual.hpp>
#include <ohxl/loop.hpp>

#define XLL_DEC DLLEXPORT


XLL_DEC long *qlFunctionCount() {
    static long returnValue = FUNCTION_COUNT;
    return &returnValue;
}

// Repository URL of the working copy:
// $WCURL$

//XLL_DEC long *qlInfoHighestRevisionNumber() {
//    static long returnValue = $WCREV$;
//    return &returnValue;
//}
//
//XLL_DEC char *qlInfoTimeStamp() {
//    char *date = "$WCDATE$";
//    return date;
//}
//
//#define MIXED_REVISIONS $WCMIXED?1:0$
//XLL_DEC char *qlInfoRevisionRange() {
//    #if MIXED_REVISIONS
//    #   pragma message(__FILE__ "() warning: mixed update revisions ($WCRANGE$)")
//    #endif
//    char *revRange = "$WCRANGE$";
//    return revRange;
//}
//
//#define LOCAL_MODIFICATION $WCMODS?1:0$
//XLL_DEC bool *qlInfoLocalModifications() {
//    #if LOCAL_MODIFICATION
//    #   pragma message(__FILE__ "() warning: local modifications have been found")
//    static bool result = true;
//    #else
//    static bool result = false;
//    #endif
//    return &result;
//}

// qlCalendarAdvance - manual implementation replacing the autogenerated loop
// version.  Calendar::advance gained an optional 5th parameter in the ORE fork
// of QuantLib; the typedefs in loop_calendar_manual.hpp express the resulting
// cmf5 bind signature that gensrc cannot generate.

XLL_DEC OPER *qlCalendarAdvance(
        char *calendar,
        OPER *StartDate,
        OPER *Period,
        OPER *BusinessDayConvention,
        OPER *EndOfMonth,
        OPER *Trigger) {

    boost::shared_ptr<ObjectHandler::FunctionCall> functionCall;

    try {

        functionCall = boost::shared_ptr<ObjectHandler::FunctionCall>(
            new ObjectHandler::FunctionCall("qlCalendarAdvance"));

        ObjectHandler::validateRange(Trigger, "Trigger");

        SET_SESSION_ID

        ObjectHandler::property_t StartDateCpp = ObjectHandler::convert2<ObjectHandler::property_t>(
            ObjectHandler::ConvertOper(*StartDate));

        std::string BusinessDayConventionCpp = ObjectHandler::convert2<std::string>(
            ObjectHandler::ConvertOper(*BusinessDayConvention), "BusinessDayConvention", "Following");

        bool EndOfMonthCpp = ObjectHandler::convert2<bool>(
            ObjectHandler::ConvertOper(*EndOfMonth), "EndOfMonth", false);

        QuantLib::Date StartDateLib = ObjectHandler::convert2<QuantLib::Date>(
            ObjectHandler::ConvertOper(*StartDate), "StartDate");

        std::vector<QuantLib::Period> PeriodLib =
            ObjectHandler::operToVector<QuantLib::Period>(*Period, "Period");

        QuantLib::Calendar calendarEnum =
            ObjectHandler::Create<QuantLib::Calendar>()(calendar);

        QuantLib::BusinessDayConvention BusinessDayConventionEnum =
            ObjectHandler::Create<QuantLib::BusinessDayConvention>()(BusinessDayConventionCpp);

        static XLOPER returnValue;

	typedef QuantLib::Date
		(QuantLib::Calendar::*qlCalendarAdvanceSignatureManual)(
		const QuantLib::Date&,
		const QuantLib::Period&,
		QuantLib::BusinessDayConvention,
		bool
	) const;

        QuantLibAddin::qlCalendarAdvanceBindManual bindObject =
            boost::bind(
		static_cast<qlCalendarAdvanceSignatureManual>(
                &QuantLib::Calendar::advance),
                calendarEnum,
                StartDateLib,
                boost::placeholders::_1,
                BusinessDayConventionEnum,
                EndOfMonthCpp
                );

        ObjectHandler::loop
            <QuantLibAddin::qlCalendarAdvanceBindManual, QuantLib::Period, QuantLib::Date>
            (functionCall, bindObject, Period, returnValue);

        return &returnValue;

    } catch (const std::exception &e) {
        ObjectHandler::RepositoryXL::instance().logError(e.what(), functionCall);
        return 0;
    } catch (...) {
        ObjectHandler::RepositoryXL::instance().logError("unkown error type", functionCall);
        return 0;
    }
}

void registerManualFunctions(const XLOPER &xDll) {

    Excel(xlfRegister, 0, 13, &xDll,
        // function code name
        TempStrNoSize("\x11""qlCalendarAdvance"),
        // parameter codes
        TempStrNoSize("\x08""PCPPPPP#"),
        // function display name
        TempStrNoSize("\x11""qlCalendarAdvance"),
        // comma-delimited list of parameter names
        TempStrNoSize("\x42""calendar,StartDate,Period,BusinessDayConvention,EndOfMonth,Trigger"),
        // function type (0 = hidden, 1 = worksheet)
        TempStrNoSize("\x01""1"),
        // function category
        TempStrNoSize("\x0F""QuantLib - Date"),
        // shortcut text (command macros only)
        TempStrNoSize("\x00"""),
        // path to help file
        TempStrNoSize("\x00"""),
        // function description
        TempStrNoSize("\x2E""advances a date according to a given calendar."),
        // parameter descriptions
        TempStrNoSize("\x2D""ID of Enumeration of class QuantLib::Calendar"),
        TempStrNoSize("\x1A""start date to be advanced."),
        TempStrNoSize("\x65""period(s) to advance (e.g. 2D for two days , 3W for three weeks, 6M for six months, 1Y for one year)."),
        TempStrNoSize("\x2E""rolling convention. Default value = Following."),
        TempStrNoSize("\x3F""flag to enforce end of month convention. Default value = false."),
        TempStrNoSize("\x1D""dependency tracking trigger  "));
}

void unregisterManualFunctions(const XLOPER &xDll) {

    XLOPER xlRegID;
    Excel4(xlfRegisterId, &xlRegID, 2, &xDll,
        TempStrNoSize("\x11""qlCalendarAdvance"));
    Excel4(xlfUnregister, 0, 1, &xlRegID);
}
